- id: format-xmllint
  name: Formats XML files
  description: Format XML files to match xmllint --format option
  entry: check-xmllint
  args: [-i]
  language: script
  types_or: [xml]

- id: check-xmllint
  name: Check XML files formatting
  description: Check that XML files format matches xmllint --format option
  entry: check-xmllint
  language: script
  types_or: [xml]

- id: check-xmllint-syntax
  name: Check XML files syntax
  description: Check that XML files syntax matches xmllint --noout option
  entry: check-xmllint
  args: [-c]
  language: script
  types_or: [xml]
